### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by syralie** [openalea/visualea#13]
Hi, I've been trying to install and run visualea but I've been running into issues. I was on macOS Mojave but I've tried updating to the newest macOS Monterey version 12.3.1 and am still running into the same issues.

For example, I tried conda create -n openalea -c conda-forge -c openalea openalea.visualea. This went through without issues but when I typed visualea, I received the following error message:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.Visualea-2.0.1-py2.7.egg/openalea/visualea/visualeagui.py", line 26, in <module>
    from openalea.vpltk import qt
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.vpltk-2.0.1-py2.7.egg/openalea/vpltk/qt/__init__.py", line 157, in <module>
    import openalea.vpltk.qt.designer
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.vpltk-2.0.1-py2.7.egg/openalea/vpltk/qt/designer.py", line 94, in <module>
    from openalea.vpltk.qt.uic import compileUi, compile_args
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.vpltk-2.0.1-py2.7.egg/openalea/vpltk/qt/uic.py", line 28, in <module>
    message = 'You must install %s-tools' % os.environ['QT_API']
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'QT_API'

I then tried to solve this with conda install pyqt. Then I did "visualea" again and got this error message:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.Visualea-2.0.1-py2.7.egg/openalea/visualea/visualeagui.py", line 29, in <module>
    from openalea.visualea.mainwindow import MainWindow
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.Visualea-2.0.1-py2.7.egg/openalea/visualea/mainwindow.py", line 30, in <module>
    from openalea.oalab.shell import get_shell_class
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.OALab-2.0.1-py2.7.egg/openalea/oalab/shell/__init__.py", line 2, in <module>
    from .shellwidget import ShellWidget
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.OALab-2.0.1-py2.7.egg/openalea/oalab/shell/shellwidget.py", line 1, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
ImportError: No module named qtconsole.rich_jupyter_widget

I then tried to solve this with conda install qtconsole, then I did "visualea" again and got this error message:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.Visualea-2.0.1-py2.7.egg/openalea/visualea/visualeagui.py", line 29, in <module>
    from openalea.visualea.mainwindow import MainWindow
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.Visualea-2.0.1-py2.7.egg/openalea/visualea/mainwindow.py", line 30, in <module>
    from openalea.oalab.shell import get_shell_class
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.OALab-2.0.1-py2.7.egg/openalea/oalab/shell/__init__.py", line 3, in <module>
    from .shell import get_shell_class
  File "/Users/see.min./miniconda3/envs/openalea/lib/python2.7/site-packages/OpenAlea.OALab-2.0.1-py2.7.egg/openalea/oalab/shell/shell.py", line 48, in <module>
    class PyCutExt(QtGui.QTextEdit, GraphicalStreamRedirection):
AttributeError: 'module' object has no attribute 'QTextEdit'.

Here's the conda list now:

#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                 py27_1001    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1  
brotlipy                  0.7.0           py27h0b31af3_1000    conda-forge
ca-certificates           2022.3.29            hecd8cb5_0  
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.0           py27h356ff06_0    conda-forge
chardet                   3.0.4           py27h8c360ce_1006    conda-forge
configparser              3.7.3            py27h8c360ce_2    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.8              py27hab9f8d5_2    conda-forge
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2                      py_0    conda-forge
docutils                  0.16             py27h8c360ce_1    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
expat                     2.4.4                he9d5cce_0  
future                    0.18.2           py27h8c360ce_1    conda-forge
futures                   3.3.0                    py27_0  
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.53.6               ha08cb78_1  
icu                       58.2                 h0a44026_3  
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0            py27h8c360ce_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
ipykernel                 4.10.0                   py27_0  
ipython                   4.2.1                    py27_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h9ed2024_0  
jupyter_client            5.3.4                    py27_0  
jupyter_core              4.6.1                    py27_0  
libcxx                    13.0.1               hc203e6f_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libiconv                  1.14                          3    openalea
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
markupsafe                1.1.1            py27h89ed719_1    conda-forge
more-itertools            5.0.0                      py_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
openalea-core             1.3.0                    pypi_0    pypi
openalea-deploy           2.1.8                    pypi_0    pypi
openalea-grapheditor      2.0.1                    pypi_0    pypi
openalea-misc             2.0.0                    pypi_0    pypi
openalea-oalab            2.0.1                    pypi_0    pypi
openalea-visualea         2.0.1                    pypi_0    pypi
openalea-vpltk            2.0.1                    pypi_0    pypi
openalea.core             1.4.1                    py27_0    openalea
openalea.deploy           2.1.8            py27h8c360ce_2    conda-forge
openalea.grapheditor      2.0.1                         0    openalea
openalea.misc             2.0.0                         1    openalea
openalea.oalab            2.0.1                         2    openalea
openalea.visualea         2.0.1                         0    openalea
openalea.vpltk            2.0.1                    py27_0    openalea
openssl                   1.1.1n               h6c3fc93_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
path.py                   11.5.2                     py_0    conda-forge
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pcre                      8.45                 h23ab428_0  
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5           py27h8c360ce_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py27h655552a_2  
pysocks                   1.7.1            py27h8c360ce_1    conda-forge
python                    2.7.15          h8e446fc_1011_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python.app                1.3              py27h89ed719_1    conda-forge
python_abi                2.7                     1_cp27m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyzmq                     18.1.0           py27h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.11.2             pyhd3eb1b0_0  
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scandir                   1.10.0           py27h89ed719_1    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.7.0           pyhd3eb1b0_1001  
sip                       4.19.8           py27h0a44026_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    1.8.5                    py27_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
sqlite                    3.38.2               hb516253_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   5.1.1            py27h1de35cc_0  
traitlets                 4.3.3            py27h8c360ce_1    conda-forge
typing                    3.7.4.1          py27h8c360ce_1    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h23ab428_0  
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge

I saw on another closed issue thread that it should be openalea.vpltk 2.0.2 instead. However when I tried conda install -c openalea openalea.visualea openalea.vpltk=2.0.2, I got the following error message:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - openalea.vpltk=2.0.2 -> python[version='>=3.10,<3.11.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.6|>=3.7|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

----------------------------------------------------

Another type of error I've previously gotten when entering "visualea" into the terminal was "ImportError: No module named asyncio" since I'm using python2.7 for this installation. When I try using python3 when installing visualea I'd get error messages about conflicts etc. but I believe asyncio is a python3 module? I have since deleted the env which gave that error though.

-----------------------------------------------------

I also tried this on a Linux server and I ran into same/similar error messages.

**Comment by pradal** [comment]
Yes. Sorry. VisuAlea is not yet ported to Python 3 and PyQt5

**Comment by syralie** [comment]
I see, thanks for the prompt reply! 

Would it be possible to install and run it with python2.7? I'm not quite sure how to download pyqt4 right now though (installing pyqt=4 gives error messages).

Or is there any other way I could install and use it?

**Comment by syralie** [comment]
Hi there, sorry to disturb but are there any updates on this (or is there anyway I could install VisuAlea now and use it)? Hope to hear soon!

**Comment by pellem** [comment]
> Yes. Sorry. VisuAlea is not yet ported to Python 3 and PyQt5

I think it's done now, maybe should we close this issue ?
