### ISSUE TITLE
[VisuAlea] Error due to a local import 

### ISSUE THREAD

**Issue by pradal** [openalea/visualea#23]
When running visualea, there is an error:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/pradal/miniconda3/envs/tstvisu/lib/python3.10/site-packages/OpenAlea.Visualea-2.3.1-py3.9.egg/openalea/visualea/visualeagui.py", line 32, in <module>
>     from openalea.visualea.mainwindow import MainWindow
>   File "/Users/pradal/miniconda3/envs/tstvisu/lib/python3.10/site-packages/OpenAlea.Visualea-2.3.1-py3.9.egg/openalea/visualea/mainwindow.py", line 51, in <module>
>     from openalea.visualea import dataflowview, helpwidget, metainfo, ui_mainwindow
>   File "/Users/pradal/miniconda3/envs/tstvisu/lib/python3.10/site-packages/OpenAlea.Visualea-2.3.1-py3.9.egg/openalea/visualea/ui_mainwindow.py", line 445, in <module>
>     import images_rc
> ModuleNotFoundError: No module named 'images_rc'

**Comment by pradal** [comment]
This is a bug in designer.py
