### ISSUE TITLE
Ubuntu fail

### ISSUE THREAD

**Issue by jazzsta** [openalea/visualea#32]
Hello,

I installed everything in Ubuntu   with a conda environment openalea3 and with setup.py develop, and when I try to run visualeagui.py I get this message

> Traceback (most recent call last):
  File "/home/jazzsta/Model/visualea/src/openalea/visualea/visualeagui.py", line 197, in <module>
    main(sys.argv)
  File "/home/jazzsta/Model/visualea/src/openalea/visualea/visualeagui.py", line 103, in main
    app = Openalea(args)
  File "/home/jazzsta/Model/visualea/src/openalea/visualea/visualeagui.py", line 67, in __init__
    self.win = MainWindow(None)
  File "/home/jazzsta/Model/visualea/src/openalea/visualea/mainwindow.py", line 228, in __init__
    self.read_settings()
  File "/home/jazzsta/Model/visualea/src/openalea/visualea/mainwindow.py", line 370, in read_settings
    settings = Settings()
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/site-packages/openalea.core-2.2.0-py3.9.egg/openalea/core/singleton.py", line 42, in __call__
    return weakref.proxy(Singleton.__call__(cls, *args, **kw))
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/site-packages/openalea.core-2.2.0-py3.9.egg/openalea/core/singleton.py", line 33, in __call__
    cls._instance = super(Singleton, cls).__call__(*args, **kw)
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/site-packages/openalea.core-2.2.0-py3.9.egg/openalea/core/settings.py", line 153, in __init__
    self.read()
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/site-packages/openalea.core-2.2.0-py3.9.egg/openalea/core/settings.py", line 168, in read
    settingsLogger.debug("Reading configuration file from " + self.configfile)
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/logging/__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/home/jazzsta/miniconda3/envs/openalea3/lib/python3.9/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes 1 positional argument but 3 were given
 
Process finished with exit code 1

>

**Comment by pradal** [comment]
Just run visualea in a shell.

**Comment by jazzsta** [comment]
Ok I updated openalea.core and it works now :-)
