### ISSUE TITLE
SyntaxError: invalid syntax (trunk_parameters.py, line 51)

### ISSUE THREAD

**Issue by Bodata** [openalea/visualea#34]
I have installed openalea on a windows 10 machine.

I am not a python expert.
I use Python 3.9
Installed visualea but could not get it to run with the command "visualea" as stated in the documentation.

So i went to my ......\anaconda3\envs\openalea\Scripts directory.

There i run  

````
python visualea

````
I get the program started but when i try to open Demo_WeberPenn  i get:

````
Traceback (most recent call last):
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.visualea-2.3.3-py3.9.egg\openalea\visualea\util.py", line 78, in wrapped
    return f(*args)
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.visualea-2.3.3-py3.9.egg\openalea\visualea\node_treeview.py", line 859, in edit_node
    self.main_win().open_compositenode(obj)
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.visualea-2.3.3-py3.9.egg\openalea\visualea\mainwindow.py", line 495, in open_compositenode
    node = factory.instantiate()
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.core-2.3.1-py3.9.egg\openalea\core\compositenode.py", line 163, in instantiate
    node = self.instantiate_node(vid, call_stack)
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.core-2.3.1-py3.9.egg\openalea\core\compositenode.py", line 358, in instantiate_node
    node = factory.instantiate(call_stack)
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.core-2.3.1-py3.9.egg\openalea\core\node.py", line 1156, in instantiate
    module = self.get_node_module()
  File "c:\my_path\anaconda3\envs\openalea\lib\site-packages\openalea.core-2.3.1-py3.9.egg\openalea\core\node.py", line 1301, in get_node_module
    importlib.import_module(_nodemodule_name)
  File "C:\my_path\anaconda3\envs\openalea\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1030, in _gcd_import
  File "", line 1007, in _find_and_load
  File "", line 986, in _find_and_load_unlocked
  File "", line 680, in _load_unlocked
  File "", line 846, in exec_module
  File "", line 983, in get_code
  File "", line 913, in source_to_code
  File "", line 228, in _call_with_frames_removed
SyntaxError: invalid syntax (trunk_parameters.py, line 51)

````
There seems to be a pull request that is not merged.

[https://github.com/openalea/weberpenn/pulls](https://github.com/openalea/weberpenn/pulls)

When i manualy added the diffs i got it to work, only it does not seem very stable though.

**Comment by pradal** [comment]
This problem has been solved in weberpenn
