### ISSUE TITLE
Error when using send to console

### ISSUE THREAD

**Issue by pradal** [openalea/visualea#4]
In VisuAlea, when running sendtoconsole, the following error is raised:

```
  File "/Users/pradal/devlp/git/visualea/src/openalea/visualea/graph_operator/__init__.py", line 115, in wrappedGOPNoBool
    return func(*args, **kwargs)
  File "/Users/pradal/devlp/git/visualea/src/openalea/visualea/graph_operator/port.py", line 107, in port_send_to_console
    interpreter.runsource("%s\n" % result)
  File "/Users/pradal/devlp/git/core/src/openalea/core/interpreter/__init__.py", line 71, in runsource
    code = compile(source, filename, symbol)
TypeError: expected a readable buffer object
```

**Comment by pradal** [comment]
Now the error is:

> Traceback (most recent call last):
>   File "/Users/pradal/miniconda3/envs/tstvisu/lib/python3.10/site-packages/OpenAlea.Visualea-2.3.2-py3.9.egg/openalea/visualea/node_treeview.py", line 1038, in startDrag
>     drag.setHotSpot(QtCore.QPoint(pixmap.width() / 2, pixmap.height() / 2))
> TypeError: arguments did not match any overloaded call:
>   QPoint(): too many arguments
>   QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
>   QPoint(a0: QPoint): argument 1 has unexpected type 'float'
